services:
  cryptomator-vault-sync:
    image: ghcr.io/chrschu90/cryptomator-vault-sync:1
    container_name: cryptomator-vault-sync
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      CRYPTOMATOR_VAULT_PASSWORD_FILE: /config/vault-password
      SYNC_CRON: "*/5 * * * *"
      RSYNC_DELETE: false
      RSYNC_EXCLUDE_FILE: /config/rsync-exclude.txt
      UPSTREAM_ENABLED: true
      #UPSTREAM_CHECK: true # Optional rclone check after successful upstream sync/copy
      UPSTREAM_FAIL_ACTION: continue
      UPSTREAM_MODE: sync
      UPSTREAM_DESTINATIONS: remote:CryptomatorVault
      UPSTREAM_CONFIG: /config/rclone.conf
      UPSTREAM_EXTRA_ARGS:
      UPSTREAM_START_DELAY_SECONDS: 0
      TZ: Europe/Berlin
    volumes:
      - /example/sync:/sync:ro
      - /example/config:/config:ro
      - /example/vault:/vault-encrypted
      - /example/state:/state