services:
  cryptomator-vault-sync:
    image: ghcr.io/chrschu90/cryptomator-vault-sync:1
    container_name: cryptomator-vault-sync
    cap_add:
      - SYS_ADMIN                                         # Required
    devices:
      - /dev/fuse:/dev/fuse                               # Required 
    security_opt:
      - apparmor:unconfined                               # Required
    environment:
      CRYPTOMATOR_VAULT_PASSWORD: "MyVaultPassword"       # Required
      SYNC_DIR: /sync                                     # Optional [default=/sync]
      VAULT_ENCRYPTED_DIR: /vault-encrypted               # Optional [default=/vault-encrypted]
      CRYPTOMATOR_MOUNT_MODE: auto                        # Optional [default=auto] fuse, webdav, auto
      MOUNT_TIMEOUT_SECONDS: 60                           # Optional [default=60]
      SYNC_INTERVAL_MINUTES: 0                            # Optional 0=one-time [default=0]
      RSYNC_DELETE: false                                 # Optional [default=false] Do not enable unless /sync is intended to be the authoritative source!
      RSYNC_ARGS: '-rtv --no-owner --no-group --no-perms' # Optional [default=-rtv --no-owner --no-group --no-perms]
      RSYNC_EXTRA_ARGS:                                   # Optional [default=]
      HEALTHCHECK_WRITE_TEST: false                       # Optional [default=false]
      TZ: Europe/Berlin                                   # Optional
    volumes:
      - '/docker/cryptomator-vault-sync/sync:/sync:ro'           # One-Way sync source, you can also mount multiple sub-directories, but /sync must be the root directory.
      - '/docker/cryptomator-vault-sync/vault:/vault-encrypted'  # A Cryptomator vault must be inside the mount, can also be linked to a OneDrive synced directory
